export const messages = {
  en: {
    tagline:'Review price changes before you publish.',intro:'Compare old and new price exports by SKU and region. Find price increases, decreases, added and removed products, then export an offline report.',
    example:'Try the price-table example',downloadBefore:'Download before CSV',downloadAfter:'Download after CSV',star:'Saved time? Star CSV Delta on GitHub.',clear:'Clear files',local:'Your files stay in this browser. No account, no uploads.',files:'Choose your snapshots',old:'Before',new:'After',oldHint:'Your reference CSV',newHint:'Your updated CSV',choose:'Choose CSV',noFile:'No file selected',limit:'UTF-8 · 10 MiB per file · 50,000 rows',delimiter:'Delimiter',comma:'Comma',semicolon:'Semicolon',tab:'Tab',rules:'Set comparison rules',keys:'Key columns',keyHint:'Pick the columns that uniquely identify a row.',ignore:'Ignore columns',ignoreHint:'Skip timestamps or other expected changes.',numeric:'Numeric columns',numericHint:'Compare decimal values rather than their formatting.',tolerance:'Absolute tolerance',float:'Numeric comparisons use floating-point arithmetic, not exact financial decimals.',compare:'Compare snapshots',ready:'Choose both files to configure your comparison.',rows:'rows',results:'Review the difference',export:'Export HTML report',share:'The report contains your data. Share it only with people you choose.',all:'All rows',differences:'Differences',added:'Added',removed:'Removed',changed:'Changed',unchanged:'Unchanged',status:'Status',key:'Key',field:'Field',before:'Before',after:'After',empty:'Nothing here yet.',emptyHint:'Try the example or choose two CSV files to see exactly what changed.',noMatches:'No rows match this filter.',noChange:'No common-field changes',columnChanges:'Column changes',columnsAdded:'Added columns',columnsRemoved:'Removed columns',previous:'Previous',next:'Next',page:'Page',of:'of',none:'None',loading:'Reading files…',error:'Please check your input',oversize:'File exceeds the 10 MiB limit.',encoding:'Use a valid UTF-8 file.',changedSettings:'Rules changed. Compare again to refresh the results.',about:'Made for migration checks, configuration tables and price exports.',github:'Source on GitHub',reportName:'csv-delta-report.html',value:'Value',details:'All fields',help:'How comparisons work',helpText:'Row and column order do not matter. Strings are exact by default. Duplicate or empty keys stop the comparison. New and removed columns are listed separately; only common columns determine modified rows. Blank lines are skipped.',helpLimits:'Large files and reports can take a moment. Limits apply to each input. Refreshing clears all loaded data.',schemaOnly:'Column changes are reported separately from row counts.'
  },
  zh: {
    tagline:'更新价格表前，看清每一处变化。',intro:'按 SKU 和地区核对两份价格表，查出涨价、降价、新增和移除的商品，导出可离线查看的报告。',
    example:'体验价格表示例',downloadBefore:'下载旧价格表',downloadAfter:'下载新价格表',star:'节省了核对时间？欢迎在 GitHub 收藏项目。',clear:'清空文件',local:'文件只在当前浏览器处理，无需账号，不上传数据。',files:'选择两份快照',old:'旧文件',new:'新文件',oldHint:'作为基准的 CSV',newHint:'更新后的 CSV',choose:'选择 CSV',noFile:'尚未选择文件',limit:'UTF-8 · 每份最多 10 MiB · 50,000 行',delimiter:'分隔符',comma:'逗号',semicolon:'分号',tab:'制表符',rules:'设置比较规则',keys:'主键列',keyHint:'选择能唯一识别一行的列，可多选。',ignore:'忽略列',ignoreHint:'跳过时间戳等预期变化。',numeric:'数值列',numericHint:'比较十进制数值，忽略格式差异。',tolerance:'绝对容差',float:'数值比较使用浮点运算，不适用于要求精确十进制的财务核算。',compare:'比较快照',ready:'选择两份文件后即可设置比较规则。',rows:'行',results:'查看差异',export:'导出 HTML 报告',share:'报告包含你的数据，请自行选择分享对象。',all:'全部',differences:'仅差异',added:'新增',removed:'删除',changed:'修改',unchanged:'未变',status:'状态',key:'主键',field:'字段',before:'旧值',after:'新值',empty:'差异将在这里显示。',emptyHint:'体验示例或选择两份 CSV，查看具体变化。',noMatches:'没有符合筛选条件的行。',noChange:'共同字段未变',columnChanges:'列变化',columnsAdded:'新增列',columnsRemoved:'删除列',previous:'上一页',next:'下一页',page:'第',of:'/',none:'无',loading:'正在读取文件…',error:'请检查输入',oversize:'文件超过 10 MiB 上限。',encoding:'请使用有效的 UTF-8 文件。',changedSettings:'规则已变更，请重新比较以更新结果。',about:'适用于数据库迁移核对、配置表和价格表导出。',github:'GitHub 源码',reportName:'csv-delta-report.html',value:'值',details:'全部字段',help:'比较规则说明',helpText:'行列重排不会产生差异。默认精确比较字符串；重复或空主键会中止比较。新增、删除列单独报告，只有共同列决定行是否修改。空白行会被跳过。',helpLimits:'大文件和报告可能需要稍等。限制适用于每份输入；刷新页面会清空数据。',schemaOnly:'列变化单独展示，不计入行修改数量。'
  }
};
